### PR TITLE
CivicPatterns Cleanup/Extension sprint

### PR DESCRIPTION
**Pull request by pudo**
@lucychambers and I are doing a small, one-day sprint trying to consolidate the content on CivicPatterns a bit, especially by improving the linkage of patterns, importing examples, adding patterns from Code for America's repository, and removing extraneous content. 

Would love to hear your thoughts about this, @pmackay, @longhotsummer? Especially: I removed the tools section because it is slightly off the main theme, is that possibly OK?

### CODE REVIEW

**Comment by longhotsummer** [comment]
:+1:

**Comment by pmackay** [comment]
Bit curious why you're pulling the tools and weird fringe bits (I thought the civic checklist was cool)? I can see point of cleaning it up though, making more focussed. 

Anyway, looks good :)

**Comment by pudo** [comment]
Yeah, I just think that the fewer different things we're trying to cover, the clearer the purpose of the site will be. Right now it's about a) civic patterns, b) doing F/OSS as an NGO and c) trying to build an open innovation ecosystem (which is what the tools are aimed at). These are three fairly different things, and I think it's much cooler to say: let's focus on incentives in civic tech. That's really what most of the patterns are about, and it is **the** crucial aspect. 

I also have to confess: I disagree with the tools section to some extent. That shouldn't authorise me to remove it, the rationale for that is what I said above. But I do believe that some of these tools have now become tokenistic: everybody is doing a hack day or a challenge, or an app store. But quite often these aren't actually meant to foster a community, but rather as a fairly boring PR measure for the initiator, or as a way to frame oneself as the center of whatever trend is most cool right now. Should we really recommend these things to organisations who lack the community context to pull them off sincerely?

**Comment by pmackay** [comment]
Yes, agree with that. Onwards then! :)

**Pull request merged**
