### PR TITLE
Make patterns easier to read by not including 'what is it'

### PR DESCRIPTION
**Pull request by longhotsummer**
Would love some input on this. Basically I'm just getting rid of the 'What is it text?' so that patterns are easier to read. The text feels redundant to me.

### CODE REVIEW

**Comment by pudo** [comment]
Let's do that, agreed! I'd also like to start adding some texts to some of the patterns so we can see how that looks and works.

**Comment by longhotsummer** [comment]
Yeah, extra text would be good. Once we've got some body content for the patterns, then using something like bootstrap's "lead" CSS class to make the title text stand out.

**Comment by tmtmtmtm** [comment]
@pudo @longhotsummer here's one I did yesterday: http://civicpatterns.org/patterns/clean-room/

**Comment by tmtmtmtm** [comment]
Or http://civicpatterns.org/patterns/no-risk/ from @zararah

**Comment by longhotsummer** [comment]
I like it. If we simply bump the title blurb’s font size to 18px, it stands out nicely from the longer description.

## 

Greg Kempe
p +27 (0)78 246 1116
w  kempe.net
t  @longhotsummer

On 04 June 2014 at 6:00:12 PM, Tony Bowden (notifications@github.com) wrote:

@pudo @longhotsummer here's one I did yesterday: http://civicpatterns.org/patterns/clean-room/

**Pull request merged**
